# Generated by Django 3.2.7 on 2021-09-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Что-то', 'verbose_name_plural': 'Много Чего-то'},
        ),
    ]
